import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
if (typeof window !== "undefined") {
  if (typeof window.process === "undefined") {
    window.process = { env: {}, cwd: function() { return ""; }, kill: function() {} };
  }
  const _origRequire = window.require;
  if (_origRequire) {
    window.require = function(mod) {
      try {
        const res = _origRequire(mod);
        if (res) return res;
      } catch (e) {}
      if (mod === "child_process") {
        return {
          spawn: function() { return { on: function() {}, pid: 0, kill: function() {}, stdout: { on: function() {} }, stderr: { on: function() {} }, stdin: { write: function() {}, end: function() {} } }; },
          execFile: function(c, a, o, cb) { const f = typeof o === "function" ? o : cb; if (f) f(new Error("child_process not supported on mobile")); }
        };
      }
      if (mod === "fs" || mod === "fs/promises") {
        return { readFile: async function() { return ""; }, writeFile: async function() {}, stat: async function() { return { isFile: function() { return true; }, isDirectory: function() { return false; } }; }, mkdir: async function() {} };
      }
      if (mod === "path") {
        return { join: function(...args) { return args.filter(Boolean).join("/").replace(/\\/+/g, "/"); }, resolve: function(...args) { return args.filter(Boolean).join("/").replace(/\\/+/g, "/"); }, basename: function(p) { return p.split("/").pop() || ""; }, dirname: function(p) { return p.split("/").slice(0, -1).join("/") || "."; } };
      }
      if (mod === "electron") {
        return { webUtils: { getPathForFile: function() { return ""; } }, remote: { dialog: { showOpenDialog: async function() { return { canceled: true, filePaths: [] }; } } } };
      }
      throw new Error("Cannot find module '" + mod + "'");
    };
  }
}
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
